### ISSUE TITLE
BadDeviceToken for every push on dev and prod cert

### ISSUE THREAD

**Issue by JScripteaser** [matrix-org/sygnal#105]
Have no idea what is this. Somebody help?

`2020-04-17 10:05:35,415 [28411] INFO  sygnal.apnspushkin [1fc01ce6-285d-488c-91af-06dcacda7c66] Sending as APNs-ID bc6a234c-885d-445e-84f8-279f072d6cf6
2020-04-17 10:05:36,030 [28411] WARNING sygnal.http [1fc01ce6-285d-488c-91af-06dcacda7c66] Failed to dispatch notification.
Traceback (most recent call last):
  File "/var/www/matrix_sygnal/sygnal/http.py", line 234, in _handle_dispatch
    result = await pushkin.dispatch_notification(notif, d, context)
  File "/var/www/matrix_sygnal/sygnal/apnspushkin.py", line 227, in dispatch_notification
    log, span, device, shaved_payload, prio
  File "/var/www/matrix_sygnal/sygnal/apnspushkin.py", line 185, in _dispatch_request
    f"{response.status} {response.description}"
sygnal.exceptions.NotificationDispatchException: 400 BadDeviceToken`

**Comment by clokep** [comment]
@JScripteaser I'd suggest troubleshooting in the #sygnal:matrix.org channel.

The (not very helpful) Apple docs say this error is:
>  The specified device token was bad. Verify that the request contains a valid token and that the token matches the environment.
