### ISSUE TITLE
error in running service

### ISSUE THREAD

**Issue by anilk9096** [matrix-org/sygnal#113]
python3.7 -m sygnal.sygnal
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/root/sygnal/sygnal/__init__.py", line 16, in <module>
    from importlib_metadata import version, PackageNotFoundError
ModuleNotFoundError: No module named 'importlib_metadata'

**Comment by anilk9096** [comment]
dependencies issue
