### ISSUE TITLE
Failed to load and create pushkin for kind %s'

### ISSUE THREAD

**Issue by theodotos** [matrix-org/sygnal#124]
After the latest pull (commit cde647a55a984e2fb9422a77663d30bd49fdc753) I get the following error when I run sygnal:

```
/opt/sygnal# python -m sygnal.sygnal
Error during startup:
Traceback (most recent call last):
  File "/opt/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/sygnal/sygnal/sygnal.py", line 221, in start
    port, bind_addresses, pushgateway_api
  File "/opt/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 911, in ensureDeferred
    return _cancellableInlineCallbacks(coro)
  File "/opt/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/opt/sygnal/sygnal/sygnal.py", line 221, in start
    port, bind_addresses, pushgateway_api
  File "/opt/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/sygnal/sygnal/sygnal.py", line 194, in _make_pushkins_then_start
    "Failed to load and create pushkin for kind %s", app_cfg["type"]
builtins.RuntimeError: ('Failed to load and create pushkin for kind %s', 'apns')
```

Any idea?

**Comment by clokep** [comment]
Looks like we're still not logging the proper error here. :sigh: I'm going to make a few more improvements here and hopefully you'll be able to get the *real* exception.

You can likely get it by modifying the following lines:

https://github.com/matrix-org/sygnal/blob/cde647a55a984e2fb9422a77663d30bd49fdc753/sygnal/sygnal.py#L193-L195

And just change it to `raise` instead.

**Comment by clokep** [comment]
The changes in #125 should help show the actual error. I'd also recommend joining #sygnal:matrix.org for support.

**Comment by theodotos** [comment]
Yes it was a missing aioapns module. Thanks @clokep.
