### ISSUE TITLE
APNs: Certfile Authentication also needs a `topic` (AttributeError: 'NoneType' object has no attribute 'strip')

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/sygnal#137]
I guess nobody ran into this by now because:

* I never had any credentials to use APNs myself
    * so I always get turned away because my self-signed cert is … self-signed / not trusted by APNs
        * so I never get beyond TLS; apart from empirical testing, we've been trusting aioapns
* Riot are using keyfile auth

It leads to a pretty vague error buried in hyper-h2 buried in aioapns

```
Traceback (most recent call last):
  File "x/sygnal/sygnal/http.py", line 265, in _handle_dispatch
    result = await pushkin.dispatch_notification(notif, d, context)
  File "x/sygnal/sygnal/notifications.py", line 164, in dispatch_notification
    return await self._dispatch_notification_unlimited(n, device, context)
  File "x/sygnal/sygnal/apnspushkin.py", line 269, in _dispatch_notification_unlimited
    log, span, device, shaved_payload, prio
  File "x/sygnal/sygnal/apnspushkin.py", line 200, in _dispatch_request
    response = await self._send_notification(request)
  File "x/sygnal/sygnal/apnspushkin.py", line 468, in _send_notification
    asyncio.ensure_future(self.apns_client.send_notification(request))
  File "x/sygnal.venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 824, in adapt
    extracted = result.result()
  File "x/aioapns/aioapns/client.py", line 49, in send_notification
    response = await self.pool.send_notification(request)
  File "x/aioapns/aioapns/connection.py", line 377, in send_notification
    response = await connection.send_notification(request)
  File "x/aioapns/aioapns/connection.py", line 176, in send_notification
    headers=headers
  File "x/sygnal.venv/lib/python3.7/site-packages/h2/connection.py", line 771, in send_headers
    headers, self.encoder, end_stream
  File "x/sygnal.venv/lib/python3.7/site-packages/h2/stream.py", line 866, in send_headers
    headers, encoder, hf, hdr_validation_flags
  File "x/sygnal.venv/lib/python3.7/site-packages/h2/stream.py", line 1252, in _build_headers_frames
    encoded_headers = encoder.encode(headers)
  File "x/sygnal.venv/lib/python3.7/site-packages/hpack/hpack.py", line 249, in encode
    for header in headers:
  File "x/sygnal.venv/lib/python3.7/site-packages/h2/utilities.py", line 496, in inner
    for header in headers:
  File "x/sygnal.venv/lib/python3.7/site-packages/h2/utilities.py", line 441, in _validate_host_authority_header
    for header in headers:
  File "x/sygnal.venv/lib/python3.7/site-packages/h2/utilities.py", line 335, in _reject_pseudo_header_fields
    for header in headers:
  File "x/sygnal.venv/lib/python3.7/site-packages/h2/utilities.py", line 291, in _reject_connection_header
    for header in headers:
  File "x/sygnal.venv/lib/python3.7/site-packages/h2/utilities.py", line 275, in _reject_te
    for header in headers:
  File "x/sygnal.venv/lib/python3.7/site-packages/h2/utilities.py", line 88, in _secure_headers
    for header in headers:
  File "x/sygnal.venv/lib/python3.7/site-packages/h2/utilities.py", line 547, in _strip_connection_headers
    for header in headers:
  File "x/sygnal.venv/lib/python3.7/site-packages/h2/utilities.py", line 540, in _strip_surrounding_whitespace
    yield (header[0].strip(), header[1].strip())
AttributeError: 'NoneType' object has no attribute 'strip'
```

If anyone is out there with this issue, then I'm on it soon :)

**Comment by reivilibre** [comment]
On further investigation, this issue probably does not occur with real APNs certificates, because they have a UID field which is read by `aioapns` and then used as the topic.

My self-signed snake oil certificate does not have this field, though.

This bug is invalid.
