### ISSUE TITLE
Tests: noisy exceptions in test_apns.py

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/sygnal#148]
In test_apns.py, this:

```python
self.apns_pushkin_snotif = MagicMock()
self.sygnal.pushkins[PUSHKIN_ID]._send_notification = self.apns_pushkin_snotif
```

causes noisy exceptions in some of the tests:

```
Traceback (most recent call last):
  File "/home/oli/MatrixNV/MNV2020/sygnal/sygnal/http.py", line 265, in _handle_dispatch
    result = await pushkin.dispatch_notification(notif, d, context)
  File "/home/oli/MatrixNV/MNV2020/sygnal/sygnal/notifications.py", line 164, in dispatch_notification
    return await self._dispatch_notification_unlimited(n, device, context)
  File "/home/oli/MatrixNV/MNV2020/sygnal/sygnal/apnspushkin.py", line 278, in _dispatch_notification_unlimited
    return await self._dispatch_request(
  File "/home/oli/MatrixNV/MNV2020/sygnal/sygnal/apnspushkin.py", line 210, in _dispatch_request
    response = await self._send_notification(request)
TypeError: object function can't be used in 'await' expression
```

Not harmful, but noisy and distracting when looking for issues in other tests.

**Comment by clokep** [comment]
The return value of the mock needs to be an awaitable -- we have many examples of this in the Synapse code.
