### ISSUE TITLE
Push notifications not working..Error in sygnal gateway.

### ISSUE THREAD

**Issue by k-sathireddy** [matrix-org/sygnal#15]
Push notifications are not working. I got the following errors in sygnal log:

2017-04-07 17:31:38,068 sygnal.apnspushkin INFO '{'aps': {'content-available': 1, 'sound': u'default', 'badge': 1, 'alert': {'loc-args': [u'@user111:my.domain.name', u'test msg 2'], 'loc-key': 'MSG_FROM_USER_WITH_CONTENT'}}, 'room_id': u'!KtyhAUyBMXMbpOVdXC:my.domain.name'}' -> /jELQ5q651Af+obOIek7CPonYcqd4W62rbh6wmEuBF0=
2017-04-07 17:31:38,068 pushbaby.pushconnection INFO Establishing new connection to ('gateway.push.apple.com', 2195)
2017-04-07 17:31:38,312 pushbaby.pushconnection WARNING Couldn't set socket timeout (only works on Linux >= 2.6.37). Unresponsive connections will take a long time to timeout and pushes during that time will be lost.
2017-04-07 17:31:38,898 pushbaby.pushconnection INFO Connection closed remotely
2017-04-07 17:31:38,899 pushbaby.pushconnection ERROR Caught exception sending push
Traceback (most recent call last):
  File "build/bdist.macosx-10.12-x86_64/egg/pushbaby/pushconnection.py", line 265, in sendpush
    res['ret'] = self._reallysend(payload, token, expiration, priority, identifier)
  File "build/bdist.macosx-10.12-x86_64/egg/pushbaby/pushconnection.py", line 285, in _reallysend
    raise ConnectionDeadException()
ConnectionDeadException
2017-04-07 17:31:38,901 pushbaby INFO Connection died: removing
2017-04-07 17:31:38,902 sygnal.apnspushkin ERROR Exception sending push

**Comment by slazht** [comment]
I got same issue

**Comment by dbkr** [comment]
```
2017-04-07 17:31:38,898 pushbaby.pushconnection INFO Connection closed remotely
```

The APNS server is closing the connection on you - you're probably sending the wrong certificate.

Please don't use the bug tracker for support requests - #matrix:matrix.org would be a better place for this.

**Comment by larry-troy** [comment]
Have you solved this problem? if so how?

**Comment by mrtshoot** [comment]
please visit my own sygnal push gateway with docker on https://github.com/mrtshoot/docker-sygnal
