### ISSUE TITLE
Docker build is broken

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/sygnal#244]
The docker build is broken, so 0.10.0 has not received a Docker build.

**Comment by richvdh** [comment]
how is it broken, for the historical record?

**Comment by reivilibre** [comment]
<details> 
  <summary>console output</summary>
```
Sending build context to Docker daemon  1.083MB
Step 1/7 : FROM python:3.7-slim as builder
 ---> ea0de2b0962c
Step 2/7 : COPY . /sygnal/
 ---> Using cache
 ---> 2f28bbf8e857
Step 3/7 : RUN pip install --prefix="/install" --no-warn-script-location /sygnal
 ---> Running in 68891768efb9
Processing /sygnal
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp8w3mnp0h
         cwd: /tmp/pip-req-build-2wphgo07
    Complete output (42 lines):
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 151, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-a5h_d_pu/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-a5h_d_pu/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 259, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/tmp/pip-build-env-a5h_d_pu/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 76, in <module>
        long_description=read_file(("README.rst",)),
      File "/tmp/pip-build-env-a5h_d_pu/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-a5h_d_pu/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 456, in __init__
        k: v for k, v in attrs.items()
      File "/usr/local/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/tmp/pip-build-env-a5h_d_pu/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 807, in finalize_options
        ep(self)
      File "/tmp/pip-build-env-a5h_d_pu/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 814, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-env-a5h_d_pu/normal/lib/python3.7/site-packages/setuptools_scm/integration.py", line 24, in version_keyword
        dist.metadata.version = _get_version(config)
      File "/tmp/pip-build-env-a5h_d_pu/normal/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 173, in _get_version
        parsed_version = _do_parse(config)
      File "/tmp/pip-build-env-a5h_d_pu/normal/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 127, in _do_parse
        version = _version_from_entrypoints(config) or _version_from_entrypoints(
      File "/tmp/pip-build-env-a5h_d_pu/normal/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 65, in _version_from_entrypoints
        version = _call_entrypoint_fn(root, config, ep.load())
      File "/tmp/pip-build-env-a5h_d_pu/normal/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 46, in _call_entrypoint_fn
        return fn(root, config=config)
      File "/tmp/pip-build-env-a5h_d_pu/normal/lib/python3.7/site-packages/setuptools_scm/git.py", line 115, in parse
        require_command("git")
      File "/tmp/pip-build-env-a5h_d_pu/normal/lib/python3.7/site-packages/setuptools_scm/utils.py", line 142, in require_command
        raise OSError("%r was not found" % name)
    OSError: 'git' was not found
    ----------------------------------------
WARNING: Discarding file:///sygnal. Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp8w3mnp0h Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp8w3mnp0h Check the logs for full command output.
The command '/bin/sh -c pip install --prefix="/install" --no-warn-script-location /sygnal' returned a non-zero code: 1
```
</details>

**Comment by richvdh** [comment]
huh... how has it ever worked?

**Comment by reivilibre** [comment]
> huh... how has it ever worked?

Looks like git was removed (accidentally) in #236: https://github.com/matrix-org/sygnal/pull/236/files#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddcL21.
