### ISSUE TITLE
CA_MD_TOO_WEAK for dev APNS certificate

### ISSUE THREAD

**Issue by irl** [matrix-org/sygnal#260]
**Describe the bug**
A freshly signed dev APNS certificate causes a crash with openssl error below.

**To Reproduce**
1. Use the sygnal docker container
2. Use a freshly signed dev APNS certificate
3. Check logs

**Expected behavior**
Certificate is accepted.

**Screenshots**

```
sygnal_1   | Using configuration file: /config/sygnal.yaml
sygnal_1   | 2021-10-25 12:47:46,830 [1] INFO  __main__ Starting Prometheus Server on 0.0.0.0 port 8000
sygnal_1   | 2021-10-25 12:47:46,836 [1] INFO  __main__ Importing pushkin module: sygnal.apnspushkin
sygnal_1   | 2021-10-25 12:47:46,853 [1] INFO  __main__ Creating pushkin: ApnsPushkin
sygnal_1   | 2021-10-25 12:47:46,855 [1] ERROR __main__ Failed to load and create pushkin for kind 'apns'
sygnal_1   | Error during startup:
sygnal_1   | Traceback (most recent call last):
sygnal_1   |   File "/usr/local/lib/python3.7/site-packages/sygnal/sygnal.py", line 199, in start
sygnal_1   |     yield ensureDeferred(self.make_pushkins_then_start())
sygnal_1   |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1130, in ensureDeferred
sygnal_1   |     return Deferred.fromCoroutine(coro)
sygnal_1   |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1106, in fromCoroutine
sygnal_1   |     return _cancellableInlineCallbacks(coro)
sygnal_1   |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1816, in _cancellableInlineCallbacks
sygnal_1   |     _inlineCallbacks(None, gen, status)
sygnal_1   | --- <exception caught here> ---
sygnal_1   |   File "/usr/local/lib/python3.7/site-packages/sygnal/sygnal.py", line 199, in start
sygnal_1   |     yield ensureDeferred(self.make_pushkins_then_start())
sygnal_1   |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
sygnal_1   |     result = current_context.run(gen.send, result)
sygnal_1   |   File "/usr/local/lib/python3.7/site-packages/sygnal/sygnal.py", line 171, in make_pushkins_then_start
sygnal_1   |     self.pushkins[app_id] = await self._make_pushkin(app_id, app_cfg)
sygnal_1   |   File "/usr/local/lib/python3.7/site-packages/sygnal/sygnal.py", line 166, in _make_pushkin
sygnal_1   |     return await clarse.create(app_name, self, app_config)
sygnal_1   |   File "/usr/local/lib/python3.7/site-packages/sygnal/notifications.py", line 132, in create
sygnal_1   |     return cls(name, sygnal, config)
sygnal_1   |   File "/usr/local/lib/python3.7/site-packages/sygnal/apnspushkin.py", line 151, in __init__
sygnal_1   |     loop=loop,
sygnal_1   |   File "/usr/local/lib/python3.7/site-packages/aioapns/client.py", line 36, in __init__
sygnal_1   |     ssl_context=ssl_context,
sygnal_1   |   File "/usr/local/lib/python3.7/site-packages/aioapns/connection.py", line 450, in __init__
sygnal_1   |     self.ssl_context.load_cert_chain(cert_file)
sygnal_1   | ssl.SSLError: [SSL: CA_MD_TOO_WEAK] ca md too weak (_ssl.c:3911)
```

Similar issues:

* https://github.com/jazzband/django-push-notifications/issues/532
* https://developer.apple.com/forums/thread/668393

**Comment by callahad** [comment]
We believe JWT-based authentication, which is supported by Sygnal for APNS, is a reasonable alternative, and preferable to downgrading the security level of OpenSSL in our container.

@irl: If it is not possible for you to use JWTs, please reply with why and we can re-open this issue and fix it.
