### ISSUE TITLE
build failed due to aioapns dependency version

### ISSUE THREAD

**Issue by laurent-dol** [matrix-org/sygnal#293]
https://github.com/matrix-org/sygnal/blob/bd1c408902988c624ee6c87e97ec6af454698156/setup.py#L25

aioapns 2.1 introduced a breaking change. (remove loop on APNS instantiation).

to fix it, set the dep to : 

    "aioapns==2.0.2",

**Comment by DMRobertson** [comment]
Hi @laurent-dol, could you explain what the breakage is here---which build failed, and how?

**Comment by laurent-dol** [comment]
The build with the Dockerfile.
It doesn't failed, but the created image fails to run with a script error introduced by the new aioapns version (when an apns app id is configured).

**Comment by DMRobertson** [comment]
> the created image fails to run with a script error

Interesting---could you share traceback from the error message?

**Comment by laurent-dol** [comment]
2022-01-27 16:20:19,618 [1] INFO  __main__ Importing pushkin module: sygnal.apnspushkin
2022-01-27 16:20:19,657 [1] INFO  __main__ Creating pushkin: ApnsPushkin
2022-01-27 16:20:19,659 [1] ERROR __main__ Failed to load and create pushkin for kind 'apns'
Error during startup:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sygnal/sygnal.py", line 228, in start
    yield ensureDeferred(self.make_pushkins_then_start())
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1130, in ensureDeferred
    return Deferred.fromCoroutine(coro)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1106, in fromCoroutine
    return _cancellableInlineCallbacks(coro)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1816, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/sygnal/sygnal.py", line 228, in start
    yield ensureDeferred(self.make_pushkins_then_start())
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/usr/local/lib/python3.7/site-packages/sygnal/sygnal.py", line 200, in make_pushkins_then_start
    self.pushkins[app_id] = await self._make_pushkin(app_id, app_cfg)
  File "/usr/local/lib/python3.7/site-packages/sygnal/sygnal.py", line 195, in _make_pushkin
    return await clarse.create(app_name, self, app_config)
  File "/usr/local/lib/python3.7/site-packages/sygnal/notifications.py", line 169, in create
    return cls(name, sygnal, config)
  File "/usr/local/lib/python3.7/site-packages/sygnal/apnspushkin.py", line 188, in __init__
    loop=loop,
builtins.TypeError: __init__() got an unexpected keyword argument 'loop'

**Comment by DMRobertson** [comment]
Ahh, I see! I thought when you said "remove loop" you meant the change [here](https://github.com/Fatal1ty/aioapns/pull/30/files#diff-b5fd6eafcc18782b2af25fbd465ad8c577a30c21d1eb204cf3fb1fdd30dbb961L18-R18) to limit the number of times aioapns will repeat a retry loop. But instead the loop argument was removed in https://github.com/Fatal1ty/aioapns/pull/32. I'm not sure what the reason for that was, but I'd guess it's related to this note from [the Python 3.10 changelog](https://docs.python.org/3/whatsnew/3.10.html#deprecated):

> asyncio.get_event_loop() now emits a deprecation warning if there is no running event loop. In the future it will be an alias of get_running_loop(). asyncio functions which implicitly create Future or Task objects now emit a deprecation warning if there is no running event loop and no explicit loop argument is passed: ensure_future(), wrap_future(), gather(), shield(), as_completed() and constructors of Future, Task, StreamReader, StreamReaderProtocol. (Contributed by Serhiy Storchaka in bpo-39529.)

Pinning the dependency sounds like the best way to go. Thank you for reporting!
