### ISSUE TITLE
Failed to install sygnal

### ISSUE THREAD

**Issue by Wekhrozomedo** [matrix-org/sygnal#64]
```
~/matrix/sygnal$ sudo python3.7 setup.py install
running install
Checking .pth file support in /usr/local/lib/python3.7/dist-packages/
/usr/bin/python3.7 -E -c pass
TEST PASSED: /usr/local/lib/python3.7/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing matrix_sygnal.egg-info/PKG-INFO
writing dependency_links to matrix_sygnal.egg-info/dependency_links.txt
writing requirements to matrix_sygnal.egg-info/requires.txt
writing top-level names to matrix_sygnal.egg-info/top_level.txt
reading manifest file 'matrix_sygnal.egg-info/SOURCES.txt'
writing manifest file 'matrix_sygnal.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying matrix_sygnal.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying matrix_sygnal.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying matrix_sygnal.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying matrix_sygnal.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying matrix_sygnal.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    long_description=read("README.rst"),
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```

**Comment by richvdh** [comment]
I'm afraid it works fine for me, so I suspect this is something specific to your environment. Have you tried using a virtualenv instead of installing as root?

**Comment by richvdh** [comment]
...
