### ISSUE TITLE
Can't send APNs Push - Attached to a different loop Error

### ISSUE THREAD

**Issue by Graphicscore** [matrix-org/sygnal#78]
I'm getting weird connection errors but no idea what's wrong
I am using python 3.7 as stated in the readme

```
2019-12-20 08:41:27,323 [25792] INFO  twisted SygnalLoggedSite starting on 5000
2019-12-20 08:41:27,323 [25792] INFO  twisted Starting factory <sygnal.http.SygnalLoggedSite object at 0x7fd5b5d1c610>
2019-12-20 08:41:32,531 [25792] INFO  sygnal.apnspushkin [b14fe7c7-ae0c-43bf-8dd7-d379309a78b6] Sending as APNs-ID 23d0655b-3336-4af2-9fe9-7876e00c75fa
2019-12-20 08:41:32,532 [25792] ERROR aioapns Could not connect to server: Task <Task pending coro=<APNs.send_notification() running at /usr/local/lib/python3.7/dist-packages/aioapns/client.py:49> cb=[Deferred.fromFuture.<locals>.adapt() at /usr/lib/python3/dist-packages/twisted/internet/defer.py:819]> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.7/asyncio/futures.py:348]> attached to a different loop
2019-12-20 08:41:32,532 [25792] WARNING aioapns Could not send notification 23d0655b-3336-4af2-9fe9-7876e00c75fa: ConnectionError
2019-12-20 08:41:33,534 [25792] ERROR aioapns Could not connect to server: Task <Task pending coro=<APNs.send_notification() running at /usr/local/lib/python3.7/dist-packages/aioapns/client.py:49> cb=[Deferred.fromFuture.<locals>.adapt() at /usr/lib/python3/dist-packages/twisted/internet/defer.py:819]> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.7/asyncio/futures.py:348]> attached to a different loop
2019-12-20 08:41:33,534 [25792] WARNING aioapns Could not send notification 23d0655b-3336-4af2-9fe9-7876e00c75fa: ConnectionError
2019-12-20 08:41:34,535 [25792] ERROR aioapns Could not connect to server: Task <Task pending coro=<APNs.send_notification() running at /usr/local/lib/python3.7/dist-packages/aioapns/client.py:49> cb=[Deferred.fromFuture.<locals>.adapt() at /usr/lib/python3/dist-packages/twisted/internet/defer.py:819]> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.7/asyncio/futures.py:348]> attached to a different loop
2019-12-20 08:41:34,536 [25792] WARNING aioapns Could not send notification 23d0655b-3336-4af2-9fe9-7876e00c75fa: ConnectionError
2019-12-20 08:41:35,537 [25792] ERROR aioapns Could not connect to server: Task <Task pending coro=<APNs.send_notification() running at /usr/local/lib/python3.7/dist-packages/aioapns/client.py:49> cb=[Deferred.fromFuture.<locals>.adapt() at /usr/lib/python3/dist-packages/twisted/internet/defer.py:819]> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.7/asyncio/futures.py:348]> attached to a different loop
2019-12-20 08:41:35,537 [25792] WARNING aioapns Could not send notification 23d0655b-3336-4af2-9fe9-7876e00c75fa: ConnectionError
2019-12-20 08:41:35,537 [25792] ERROR aioapns Failed to connect after 4 attempts.
2019-12-20 08:41:35,538 [25792] WARNING sygnal.apnspushkin [b14fe7c7-ae0c-43bf-8dd7-d379309a78b6] Temporary failure, will retry in 10 seconds
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aioapns/connection.py", line 335, in acquire
    connection = await self.create_connection()
  File "/usr/local/lib/python3.7/dist-packages/aioapns/connection.py", line 429, in create_connection
    ssl=self.ssl_context
  File "/usr/lib/python3.7/asyncio/base_events.py", line 905, in create_connection
    type=socket.SOCK_STREAM, proto=proto, flags=flags, loop=self)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1275, in _ensure_resolved
    proto=proto, flags=flags)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 784, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
RuntimeError: Task <Task pending coro=<APNs.send_notification() running at /usr/local/lib/python3.7/dist-packages/aioapns/client.py:49> cb=[Deferred.fromFuture.<locals>.adapt() at /usr/lib/python3/dist-packages/twisted/internet/defer.py:819]> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.7/asyncio/futures.py:348]> attached to a different loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/sygnal/sygnal/apnspushkin.py", line 152, in _dispatch_request
    response = await self._send_notification(request)
  File "/home/user/sygnal/sygnal/apnspushkin.py", line 412, in _send_notification
    asyncio.ensure_future(self.apns_client.send_notification(request))
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 821, in adapt
    extracted = result.result()
  File "/usr/local/lib/python3.7/dist-packages/aioapns/client.py", line 49, in send_notification
    response = await self.pool.send_notification(request)
  File "/usr/local/lib/python3.7/dist-packages/aioapns/connection.py", line 360, in send_notification
    connection = await self.acquire()
  File "/usr/local/lib/python3.7/dist-packages/aioapns/connection.py", line 339, in acquire
    raise ConnectionError()
aioapns.exceptions.ConnectionError
```

**Comment by richvdh** [comment]
I'm assuming this is no longer an issue. let us know if it is.

**Comment by Sr-Preet** [comment]
I'm getting the same issue, can you please help?

**Comment by Graphicscore** [comment]
@Sr-Preet If I remember right I didn't install the dependency correctly

**Comment by Sr-Preet** [comment]
Can you name the dependency please.

**Comment by frank-besson** [comment]
I am also having this error!

**Comment by Graphicscore** [comment]
@frank-besson I ended up switching to the docker image and it worked.

**Comment by j4hangir** [comment]
I get the same error when doing this:

```python

if __name__ == '__main__':
    # loop = asyncio.get_event_loop()
    # loop.run_until_complete(main())
    asyncio.run(main())
```

However, the commented lines work perfectly fine...!
