### ISSUE TITLE
Docker Image is not working

### ISSUE THREAD

**Issue by git1873** [matrix-org/sygnal#83]
Running the image from https://hub.docker.com/r/matrixdotorg/sygnal gives back these errors:

```
2020-02-29 16:30:51,604 [1] INFO  twisted Received SIGINT, shutting down.
Unhandled error in Deferred:
2020-02-29 16:30:51,639 [1] CRITICAL twisted Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sygnal/sygnal.py", line 301, in <module>
    sygnal.run()
  File "/usr/local/lib/python3.7/site-packages/sygnal/sygnal.py", line 186, in run
    self._make_pushkins_then_start(port, bind_addresses, pushgateway_api)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 911, in ensureDeferred
    return _cancellableInlineCallbacks(coro)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.7/site-packages/sygnal/sygnal.py", line 169, in _make_pushkins_then_start
    sys.exit(1)
builtins.SystemExit: 1

2020-02-29 16:30:51,642 [1] CRITICAL twisted 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.7/site-packages/sygnal/sygnal.py", line 169, in _make_pushkins_then_start
    sys.exit(1)
SystemExit: 1
```

A sygnal.yaml has been provided in /sygnal.yaml with the content of sygnal.yaml.sample.

**Comment by richvdh** [comment]
the docker image is unmaintained. I've removed it as per #90.
