### ISSUE TITLE
Behaviour when client cert is invalid

### ISSUE THREAD

**Issue by dbkr** [matrix-org/sygnal#9]

**Comment by abeluck** [comment]
I keep getting errors like this when using apns:

```
2018-11-20 14:39:59,518 pushbaby.pushconnection ERROR Caught exception opening connection
Traceback (most recent call last):
  File "/usr/local/sygnal/venv/local/lib/python2.7/site-packages/pushbaby/pushconnection.py", line 244, in send
    self._open_connection()
  File "/usr/local/sygnal/venv/local/lib/python2.7/site-packages/pushbaby/pushconnection.py", line 99, in _open_connection
    mysock, keyfile=self.keyfile, certfile=self.certfile
  File "/usr/local/sygnal/venv/local/lib/python2.7/site-packages/gevent/_sslgte279.py", line 695, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/sygnal/venv/local/lib/python2.7/site-packages/gevent/_sslgte279.py", line 198, in __init__
    self._context.load_cert_chain(certfile, keyfile)
SSLError: [SSL] PEM lib (_ssl.c:2699)
```

I wonder if the format of the key is wrong?

What format should the apns keyfile be in?
