### ISSUE TITLE
Unit tests raise Exception in setUp after successfully passing

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/sygnal#92]
This isn't critical, as the tests appear to be passing. However, it's not a great reassurance to see errors being thrown to the console.

```
Traceback (most recent call last):
  File "/home/will/git/sygnal/venv/lib/python3.7/site-packages/twisted/internet/utils.py", line 217, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/will/git/sygnal/tests/testutils.py", line 50, in setUp
    self.sygnal._make_pushkins_then_start(0, [], None)
  File "/home/will/git/sygnal/venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 911, in ensureDeferred
    return _cancellableInlineCallbacks(coro)
  File "/home/will/git/sygnal/venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/home/will/git/sygnal/venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/will/git/sygnal/sygnal/sygnal.py", line 169, in _make_pushkins_then_start
    sys.exit(1)
builtins.SystemExit: 1
```

**Comment by reivilibre** [comment]
Python loves exceptions for flow control...

The approach to exiting is to throw a SystemExit (subclass of BaseException) as you have witnessed.

I don't remember seeing this from last year though... Agree it is messy.

**Comment by reivilibre** [comment]
I can't reproduce, assuming the world has moved and this has been fixed?

**Comment by clokep** [comment]
I also can't reproduce. CI isn't seeing it either.
